name: XSLT Tests

on:
  push:
    branches: [ main, develop, tests ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Job to discover available test cases
  discover-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      test-count: ${{ steps.count.outputs.test-count }}
      test-list: ${{ steps.list.outputs.test-list }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Count test cases
      id: count
      run: |
        cd tests
        TEST_COUNT=$(find test-cases -maxdepth 1 -type d | grep -v "^test-cases$" | wc -l)
        echo "test-count=$TEST_COUNT" >> $GITHUB_OUTPUT
        echo "Found $TEST_COUNT test case(s)"
    
    - name: List test cases
      id: list
      run: |
        cd tests
        TEST_LIST=$(find test-cases -maxdepth 1 -type d | grep -v "^test-cases$" | sed 's|test-cases/||' | tr '\n' ',' | sed 's/,$//')
        echo "test-list=$TEST_LIST" >> $GITHUB_OUTPUT
        echo "Test cases: $TEST_LIST"

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [discover-tests, validate-test-fixtures]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('tests/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    
    - name: Run XSLT tests
      run: |
        cd tests
        echo "Running tests for ${{ needs.discover-tests.outputs.test-count }} test case(s): ${{ needs.discover-tests.outputs.test-list }}"
        python run_tests.py --verbose --report test_report.txt
    
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: tests/test_report.txt
        compression-level: 9
    
    - name: Display test results
      if: always()
      run: |
        echo "Test Report:"
        cat tests/test_report.txt || echo "No test report found"
        
        # Also add to GitHub Actions job summary for easy viewing
        if [ -f tests/test_report.txt ]; then
          echo "## Test Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat tests/test_report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        fi

  # Validation job to ensure test artifacts are valid
  validate-test-fixtures:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install xmllint
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libxml2-utils
      env:
        DEBIAN_FRONTEND: noninteractive
    
    - name: Validate XML test fixtures
      run: |
        echo "Validating input XML files..."
        find tests/test-cases -name "input.xml" -exec xmllint --noout {} \;
        echo "Validating expected output XML files..."
        find tests/test-cases -name "expected_output.xml" -exec xmllint --noout {} \;
        echo "All XML files are well-formed!"
    
    - name: Validate JSON configuration files
      run: |
        echo "Validating JSON configuration files..."
        find tests/test-cases -name "config.json" -exec python -m json.tool {} \; > /dev/null
        echo "All JSON files are valid!"

  # Generate coverage report if tests pass
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [discover-tests, validate-test-fixtures, test]
    if: always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Download test report
      uses: actions/download-artifact@v4
      with:
        name: test-report
        path: ./
    
    - name: Generate dynamic test coverage summary
      run: |        
        echo "# Test Coverage Summary" > coverage_summary.md
        echo "" >> coverage_summary.md
        echo "Generated on: $(date)" >> coverage_summary.md
        echo "" >> coverage_summary.md
        
        # Use the actual test results from the test job
        echo "## Test Cases" >> coverage_summary.md
        if [ -f "test_report.txt" ]; then
          echo "<!-- Debug: Found test_report.txt -->" >> coverage_summary.md
          
          # Extract test results from the detailed results section
          grep -E "^[^:]+: (PASS|FAIL)" test_report.txt > test_results.tmp 2>/dev/null || true
          
          if [ -s test_results.tmp ]; then
            echo "<!-- Debug: Found $(wc -l < test_results.tmp) test results -->" >> coverage_summary.md
            
            # Process each result
            while IFS= read -r line; do
              test_name=$(echo "$line" | cut -d: -f1)
              status=$(echo "$line" | cut -d: -f2 | tr -d ' ')
              echo "<!-- Debug: Processing '$line' -> name='$test_name' status='$status' -->" >> coverage_summary.md
              
              if [ "$status" = "PASS" ]; then
                echo "- $test_name: ✅" >> coverage_summary.md
              elif [ "$status" = "FAIL" ]; then
                echo "- $test_name: ❌" >> coverage_summary.md
              else
                echo "- $test_name: ⚠️ (Unknown status: '$status')" >> coverage_summary.md
              fi
            done < test_results.tmp
            rm -f test_results.tmp
          else
            echo "- Tests status: ⚠️ (Could not parse test results - no matching lines found)" >> coverage_summary.md
            echo "<!-- Debug: First 10 lines of test_report.txt:" >> coverage_summary.md
            head -10 test_report.txt | sed 's/^/<!-- /' | sed 's/$/ -->/' >> coverage_summary.md
          fi
        else
          echo "- Tests status: ⚠️ (Test report not found)" >> coverage_summary.md
          echo "<!-- Debug: Available files: $(ls -la) -->" >> coverage_summary.md
        fi
        
        echo "" >> coverage_summary.md
        echo "## Test Configuration" >> coverage_summary.md
        echo "- **Environment**: Python 3.12 on Ubuntu Latest" >> coverage_summary.md
        echo "- **XSLT Processor**: Saxon-HE" >> coverage_summary.md
        echo "- **Test Approach**: Each test case uses individual config.json settings" >> coverage_summary.md
        echo "- **Validation**: Semantic RDF graph comparison (XML and Turtle formats)" >> coverage_summary.md
        echo "" >> coverage_summary.md
        
        echo "## Test Statistics" >> coverage_summary.md
        echo "- **Total discovered**: ${{ needs.discover-tests.outputs.test-count }} test cases" >> coverage_summary.md
        echo "- **Test cases**: ${{ needs.discover-tests.outputs.test-list }}" >> coverage_summary.md
        echo "- **CI Environment**: Ubuntu Latest with Python 3.12" >> coverage_summary.md
        
        # Add coverage summary to GitHub Actions job summary
        cat coverage_summary.md >> $GITHUB_STEP_SUMMARY
    
    - name: Upload coverage summary
      uses: actions/upload-artifact@v4
      with:
        name: coverage-summary
        path: tests/coverage_summary.md
        compression-level: 9